# Continuous integration procedure for AppVeyor
# Based on https://github.com/rmcgibbo/python-appveyor-conda-example

environment:
  matrix:
      - PYTHON_VERSION: 2.7	
        MINICONDA: C:\Miniconda
      - PYTHON_VERSION: 3.4
        MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"


install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit)
  # - powershell .\\ci\\appveyor\\install.ps1
  # - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Dependencies and package install
  - conda install --yes ixmp pytest
  - python setup.py install

  - powershell .\\ci\\appveyor\\install-gams.ps1

build: false

test_script:
  - pytest -v tests

on_success:
  - echo Build succesful!
